### ISSUE TITLE
Create a Digital Ocean account for Code for Tuscaloosa 

### ISSUE THREAD

**Issue by Taitrnator** [CodeforTuscaloosa/Visual-UA-Budget#2]
this will be the first project to use it, but since CFA gives some credits for Digital Ocean (as well as other cloud hosting platforms) it would be a good time to create the account and setup the first project

**Comment by mleeds95** [comment]
we're not an official brigade though

**Comment by mwleeds** [comment]
I'm going to use GitHub Pages to host it once I get Jekyll working.
