### ISSUE TITLE
Write a script to make our data match expense data provided by Code for Raleigh

### ISSUE THREAD

**Issue by Taitrnator** [CodeforTuscaloosa/Visual-UA-Budget#3]
to make this project go as smooth as possible it'd be nice to have data in the same format Code for Raleigh has used so that we can use the same code for processing and displaying the data

**Comment by mwleeds** [comment]
See their data format [here](https://github.com/CodeforTuscaloosa/Visual-Town-Budget/blob/master/docs/data/CSVformatSpecs.html).
